package com.letus179.commons.entity;

// Generated 2016-5-25 13:42:21 by Hibernate Tools 4.0.0

/**
 * Citys generated by hbm2java
 */
public class Citys implements java.io.Serializable {
  
  private int id;
  
  private Long cityId;
  
  private String city;
  
  private long provinceId;
  
  private int isShow;
  
  public Citys() {
  }
  
  public Citys(int id, long provinceId, int isShow) {
    this.id = id;
    this.provinceId = provinceId;
    this.isShow = isShow;
  }
  
  public Citys(int id, Long cityId, String city, long provinceId, int isShow) {
    this.id = id;
    this.cityId = cityId;
    this.city = city;
    this.provinceId = provinceId;
    this.isShow = isShow;
  }
  
  public int getId() {
    return this.id;
  }
  
  public void setId(int id) {
    this.id = id;
  }
  
  public Long getCityId() {
    return this.cityId;
  }
  
  public void setCityId(Long cityId) {
    this.cityId = cityId;
  }
  
  public String getCity() {
    return this.city;
  }
  
  public void setCity(String city) {
    this.city = city;
  }
  
  public long getProvinceId() {
    return this.provinceId;
  }
  
  public void setProvinceId(long provinceId) {
    this.provinceId = provinceId;
  }
  
  public int getIsShow() {
    return this.isShow;
  }
  
  public void setIsShow(int isShow) {
    this.isShow = isShow;
  }
  
  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof Citys))
      return false;
    Citys castOther = (Citys) other;
    
    return (this.getId() == castOther.getId())
        && ((this.getCityId() == castOther.getCityId()) || (this.getCityId() != null
            && castOther.getCityId() != null && this.getCityId().equals(castOther.getCityId())))
        && ((this.getCity() == castOther.getCity()) || (this.getCity() != null
            && castOther.getCity() != null && this.getCity().equals(castOther.getCity())))
        && (this.getProvinceId() == castOther.getProvinceId())
        && (this.getIsShow() == castOther.getIsShow());
  }
  
  public int hashCode() {
    int result = 17;
    
    result = 37 * result + this.getId();
    result = 37 * result + (getCityId() == null ? 0 : this.getCityId().hashCode());
    result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
    result = 37 * result + (int) this.getProvinceId();
    result = 37 * result + this.getIsShow();
    return result;
  }
  
}
