package com.letus179.commons.entity;

// Generated 2016-5-25 13:42:21 by Hibernate Tools 4.0.0

/**
 * Provinces generated by hbm2java
 */
public class Provinces implements java.io.Serializable {
  
  private int id;
  
  private Long provinceId;
  
  private String province;
  
  private int orderBy;
  
  private int isShow;
  
  public Provinces() {
  }
  
  public Provinces(int id, int orderBy, int isShow) {
    this.id = id;
    this.orderBy = orderBy;
    this.isShow = isShow;
  }
  
  public Provinces(int id, Long provinceId, String province, int orderBy, int isShow) {
    this.id = id;
    this.provinceId = provinceId;
    this.province = province;
    this.orderBy = orderBy;
    this.isShow = isShow;
  }
  
  public int getId() {
    return this.id;
  }
  
  public void setId(int id) {
    this.id = id;
  }
  
  public Long getProvinceId() {
    return this.provinceId;
  }
  
  public void setProvinceId(Long provinceId) {
    this.provinceId = provinceId;
  }
  
  public String getProvince() {
    return this.province;
  }
  
  public void setProvince(String province) {
    this.province = province;
  }
  
  public int getOrderBy() {
    return this.orderBy;
  }
  
  public void setOrderBy(int orderBy) {
    this.orderBy = orderBy;
  }
  
  public int getIsShow() {
    return this.isShow;
  }
  
  public void setIsShow(int isShow) {
    this.isShow = isShow;
  }
  
  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof Provinces))
      return false;
    Provinces castOther = (Provinces) other;
    
    return (this.getId() == castOther.getId())
        && ((this.getProvinceId() == castOther.getProvinceId()) || (this.getProvinceId() != null
            && castOther.getProvinceId() != null && this.getProvinceId().equals(
            castOther.getProvinceId())))
        && ((this.getProvince() == castOther.getProvince()) || (this.getProvince() != null
            && castOther.getProvince() != null && this.getProvince()
            .equals(castOther.getProvince()))) && (this.getOrderBy() == castOther.getOrderBy())
        && (this.getIsShow() == castOther.getIsShow());
  }
  
  public int hashCode() {
    int result = 17;
    
    result = 37 * result + this.getId();
    result = 37 * result + (getProvinceId() == null ? 0 : this.getProvinceId().hashCode());
    result = 37 * result + (getProvince() == null ? 0 : this.getProvince().hashCode());
    result = 37 * result + this.getOrderBy();
    result = 37 * result + this.getIsShow();
    return result;
  }
  
}
