package com.letus179.commons.entity;

// Generated 2016-5-30 17:52:43 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Statisticalaccess generated by hbm2java
 */
public class Statisticalaccess implements java.io.Serializable {
  
  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  private String id;
  
  private User user;
  
  private int visitTimes;
  
  private Date lastVisitTime;
  
  private double liveness;
  
  private int number;
  
  private Date createTime;
  
  private Date updateTime;
  
  public Statisticalaccess() {
  }
  
  /**
   * @param id
   * @param user
   * @param visitTimes
   * @param lastVisitTime
   * @param liveness
   * @param number
   * @param createTime
   * @param updateTime
   */
  public Statisticalaccess(String id, User user, int visitTimes, Date lastVisitTime, double liveness,
      int number, Date createTime, Date updateTime) {
    super();
    this.id = id;
    this.user = user;
    this.visitTimes = visitTimes;
    this.lastVisitTime = lastVisitTime;
    this.liveness = liveness;
    this.number = number;
    this.createTime = createTime;
    this.updateTime = updateTime;
  }
  
  /**
   * @return id
   */
  public String getId() {
    return id;
  }
  
  /**
   * @param id set id
   */
  public void setId(String id) {
    this.id = id;
  }
  
  /**
   * @return user
   */
  public User getUser() {
    return user;
  }
  
  /**
   * @param user set user
   */
  public void setUser(User user) {
    this.user = user;
  }
  
  /**
   * @return visitTimes
   */
  public int getVisitTimes() {
    return visitTimes;
  }
  
  /**
   * @param visitTimes set visitTimes
   */
  public void setVisitTimes(int visitTimes) {
    this.visitTimes = visitTimes;
  }
  
  /**
   * @return lastVisitTime
   */
  public Date getLastVisitTime() {
    return lastVisitTime;
  }
  
  /**
   * @param lastVisitTime set lastVisitTime
   */
  public void setLastVisitTime(Date lastVisitTime) {
    this.lastVisitTime = lastVisitTime;
  }
  
  /**
   * @return liveness
   */
  public double getLiveness() {
    return liveness;
  }
  
  /**
   * @param liveness set liveness
   */
  public void setLiveness(double liveness) {
    this.liveness = liveness;
  }
  
  /**
   * @return number
   */
  public int getNumber() {
    return number;
  }
  
  /**
   * @param number set number
   */
  public void setNumber(int number) {
    this.number = number;
  }
  
  /**
   * @return createTime
   */
  public Date getCreateTime() {
    return createTime;
  }
  
  /**
   * @param createTime set createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
  
  /**
   * @return updateTime
   */
  public Date getUpdateTime() {
    return updateTime;
  }
  
  /**
   * @param updateTime set updateTime
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }
  
}
