package com.letus179.commons.entity;

// Generated 2016-5-25 13:42:21 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
  
  /**
   * 序号
   */
  private static final long serialVersionUID = 1L;
  
  /**
   * 主键id
   */
  private String id;
  
  /**
   * 用户真实姓名
   */
  private String realName;
  
  /**
   * 用户名
   */
  private String username;
  
  /**
   * 密码
   */
  private String password;
  
  /**
   * 盐
   */
  private int salt;
  
  /**
   * 账号是否被锁（）
   */
  private int locked;
  
  /**
   * 年龄
   */
  private Integer age;
  
  /**
   * 感情状态
   */
  private Integer loveStatus;
  
  /**
   * 性别
   */
  private Integer gender;
  
  /**
   * 个性签名
   */
  private String signature;
  
  /**
   * 身份证
   */
  private String idCard;
  
  /**
   * 手机号
   */
  private String phone;
  
  /**
   * 邮箱
   */
  private String email;
  
  /**
   * 头像地址
   */
  private String headUrl;
  
  /**
   * 生日
   */
  private Date birthday;
  
  /**
   * 手机号是否验证
   */
  private Integer isPhoneVerify;
  
  /**
   * 学历
   */
  private Integer degreeType;
  
  /**
   * 创建时间
   */
  private Date createTime;
  
  /**
   * 更新时间
   */
  private Date updateTime;
  
  /**
   * 省
   */
  private String province;
  
  /**
   * 城市
   */
  private String city;
  
  /**
   * 区
   */
  private String district;
  
  public User() {
  }
  
  public User(String id, String username, String password, int salt, int locked) {
    this.id = id;
    this.username = username;
    this.password = password;
    this.salt = salt;
    this.locked = locked;
  }
  
  /**
   * @param id
   * @param realName
   * @param username
   * @param password
   * @param salt
   * @param locked
   * @param age
   * @param loveStatus
   * @param gender
   * @param signature
   * @param idCard
   * @param phone
   * @param email
   * @param headUrl
   * @param birthday
   * @param isPhoneVerify
   * @param degreeType
   * @param createTime
   * @param updateTime
   * @param province
   * @param city
   * @param district
   */
  public User(String id, String realName, String username, String password, int salt, int locked,
      Integer age, Integer loveStatus, Integer gender, String signature, String idCard,
      String phone, String email, String headUrl, Date birthday, Integer isPhoneVerify,
      Integer degreeType, Date createTime, Date updateTime, String province, String city,
      String district) {
    super();
    this.id = id;
    this.realName = realName;
    this.username = username;
    this.password = password;
    this.salt = salt;
    this.locked = locked;
    this.age = age;
    this.loveStatus = loveStatus;
    this.gender = gender;
    this.signature = signature;
    this.idCard = idCard;
    this.phone = phone;
    this.email = email;
    this.headUrl = headUrl;
    this.birthday = birthday;
    this.isPhoneVerify = isPhoneVerify;
    this.degreeType = degreeType;
    this.createTime = createTime;
    this.updateTime = updateTime;
    this.province = province;
    this.city = city;
    this.district = district;
  }
  
  /**
   * @return id
   */
  public String getId() {
    return id;
  }
  
  /**
   * @param id set id
   */
  public void setId(String id) {
    this.id = id;
  }
  
  /**
   * @return realName
   */
  public String getRealName() {
    return realName;
  }
  
  /**
   * @param realName set realName
   */
  public void setRealName(String realName) {
    this.realName = realName;
  }
  
  /**
   * @return username
   */
  public String getUsername() {
    return username;
  }
  
  /**
   * @param username set username
   */
  public void setUsername(String username) {
    this.username = username;
  }
  
  /**
   * @return password
   */
  public String getPassword() {
    return password;
  }
  
  /**
   * @param password set password
   */
  public void setPassword(String password) {
    this.password = password;
  }
  
  /**
   * @return salt
   */
  public int getSalt() {
    return salt;
  }
  
  /**
   * @param salt set salt
   */
  public void setSalt(int salt) {
    this.salt = salt;
  }
  
  /**
   * @return locked
   */
  public int getLocked() {
    return locked;
  }
  
  /**
   * @param locked set locked
   */
  public void setLocked(int locked) {
    this.locked = locked;
  }
  
  /**
   * @return age
   */
  public Integer getAge() {
    return age;
  }
  
  /**
   * @param age set age
   */
  public void setAge(Integer age) {
    this.age = age;
  }
  
  /**
   * @return loveStatus
   */
  public Integer getLoveStatus() {
    return loveStatus;
  }
  
  /**
   * @param loveStatus set loveStatus
   */
  public void setLoveStatus(Integer loveStatus) {
    this.loveStatus = loveStatus;
  }
  
  /**
   * @return gender
   */
  public Integer getGender() {
    return gender;
  }
  
  /**
   * @param gender set gender
   */
  public void setGender(Integer gender) {
    this.gender = gender;
  }
  
  /**
   * @return signature
   */
  public String getSignature() {
    return signature;
  }
  
  /**
   * @param signature set signature
   */
  public void setSignature(String signature) {
    this.signature = signature;
  }
  
  /**
   * @return idCard
   */
  public String getIdCard() {
    return idCard;
  }
  
  /**
   * @param idCard set idCard
   */
  public void setIdCard(String idCard) {
    this.idCard = idCard;
  }
  
  /**
   * @return phone
   */
  public String getPhone() {
    return phone;
  }
  
  /**
   * @param phone set phone
   */
  public void setPhone(String phone) {
    this.phone = phone;
  }
  
  /**
   * @return email
   */
  public String getEmail() {
    return email;
  }
  
  /**
   * @param email set email
   */
  public void setEmail(String email) {
    this.email = email;
  }
  
  /**
   * @return headUrl
   */
  public String getHeadUrl() {
    return headUrl;
  }
  
  /**
   * @param headUrl set headUrl
   */
  public void setHeadUrl(String headUrl) {
    this.headUrl = headUrl;
  }
  
  /**
   * @return birthday
   */
  public Date getBirthday() {
    return birthday;
  }
  
  /**
   * @param birthday set birthday
   */
  public void setBirthday(Date birthday) {
    this.birthday = birthday;
  }
  
  /**
   * @return isPhoneVerify
   */
  public Integer getIsPhoneVerify() {
    return isPhoneVerify;
  }
  
  /**
   * @param isPhoneVerify set isPhoneVerify
   */
  public void setIsPhoneVerify(Integer isPhoneVerify) {
    this.isPhoneVerify = isPhoneVerify;
  }
  
  /**
   * @return degreeType
   */
  public Integer getDegreeType() {
    return degreeType;
  }
  
  /**
   * @param degreeType set degreeType
   */
  public void setDegreeType(Integer degreeType) {
    this.degreeType = degreeType;
  }
  
  /**
   * @return createTime
   */
  public Date getCreateTime() {
    return createTime;
  }
  
  /**
   * @param createTime set createTime
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
  
  /**
   * @return updateTime
   */
  public Date getUpdateTime() {
    return updateTime;
  }
  
  /**
   * @param updateTime set updateTime
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }
  
  /**
   * @return province
   */
  public String getProvince() {
    return province;
  }
  
  /**
   * @param province set province
   */
  public void setProvince(String province) {
    this.province = province;
  }
  
  /**
   * @return city
   */
  public String getCity() {
    return city;
  }
  
  /**
   * @param city set city
   */
  public void setCity(String city) {
    this.city = city;
  }
  
  /**
   * @return district
   */
  public String getDistrict() {
    return district;
  }
  
  /**
   * @param district set district
   */
  public void setDistrict(String district) {
    this.district = district;
  }
  
}
